package com.goldpay.util

object Banks {
    val NIGERIAN_BANKS = listOf(
        Bank("011", "Access Bank"),
        Bank("058", "Guaranty Trust Bank (GTBank)"),
        Bank("076", "Skye Bank"),
        Bank("221", "Stanbic IBTC Bank"),
        Bank("082", "Keystone Bank"),
        Bank("014", "Wema Bank"),
        Bank("063", "Diamond Bank"),
        Bank("050", "EcoBank"),
        Bank("084", "Enterprise Bank"),
        Bank("030", "FBN (First Bank)"),
        Bank("011", "First City Monument Bank (FCMB)"),
        Bank("070", "Fidelity Bank"),
        Bank("003", "FinBank"),
        Bank("011", "Heritage Bank"),
        Bank("301", "Jaiz Bank"),
        Bank("082", "Keystone Bank"),
        Bank("014", "Mainstreet Bank"),
        Bank("058", "GTBank"),
        Bank("052", "Oceanic Bank"),
        Bank("011", "Polaris Bank"),
        Bank("076", "Skye Bank"),
        Bank("068", "Standard Chartered Bank"),
        Bank("221", "Stanbic IBTC"),
        Bank("002", "Sterling Bank"),
        Bank("032", "Union Bank"),
        Bank("033", "United Bank for Africa (UBA)"),
        Bank("035", "Unity Bank"),
        Bank("057", "Zenith Bank"),
        Bank("100", "SunTrust Bank"),
        Bank("101", "Providus Bank"),
        Bank("102", "Coronation Bank"),
        Bank("103", "Titan Trust Bank"),
        Bank("104", "PalmPay"),
        Bank("105", "Kuda Bank"),
        Bank("106", "MoniePoint"),
        Bank("107", "Opay"),
        Bank("108", "ALAT by Wema"),
        Bank("109", "Carbon"),
        Bank("110", "Chipper Cash"),
        Bank("111", "PiggyVest"),
        Bank("112", "Cowrywise"),
        Bank("113", "Eyowo"),
        Bank("114", "V"),
        Bank("115", "Standard Trust Bank"),
        Bank("116", "Zenith Mobile"),
        Bank("117", "GTWorld"),
        Bank("118", "UBA Mobile"),
        Bank("119", "FBN Mobile"),
        Bank("120", "Access Mobile")
    )
}

data class Bank(val code: String, val name: String)
